### ISSUE TITLE
Escape all non-alphanumeric characters in mangled op names

### ISSUE THREAD

**Issue by rxwei** [google/swift#17]
When swift source file paths contain perfectly normal emojis (or spaces), tensorflow is not happy.

```
2018-03-26 17:42:01.497195: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Node 'op.Swift for TensorFlow.playground.16.15': Node name contains invalid characters
         [[Node: tfc_func_main.tf_partition = main.tf_partition[_device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Fatal error: Node 'op.Swift for TensorFlow.playground.16.15': Node name contains invalid characters
         [[Node: tfc_func_main.tf_partition = main.tf_partition[_device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]: file /Users/rxwei/Development/swift-source/swift/stdlib/public/TensorFlow/CompilerRuntime.swift, line 592
```

This should be fixed in [TFLowerGraph.cpp](https://github.com/google/swift/blob/tensorflow/lib/SILOptimizer/Mandatory/TFLowerGraph.cpp) - the place where we create node names should call into an "escape the name" function to handle this.

**Comment by ToucheSir** [comment]
A quick question about this: what would non-alphanumeric characters be replaced with? Considering what characters https://github.com/tensorflow/tensorflow/blob/v1.8.0/tensorflow/core/graph/graph_constructor.cc#L57 accepts, should emoji, etc. be removed entirely or converted to some ascii-friendly alphanumeric equivalent during name mangling?

**Comment by dan-zheng** [comment]
Removal is certainly the simplest solution.
The regex for allowable names is quite restrictive ([from here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/node_def.proto#L14)): `"[A-Za-z0-9.][A-Za-z0-9_./]*"`.
I don't know of any standard string escaping conventions that map onto just alphanumeric characters. 

Are there objections to simply removing invalid characters?

**Comment by dan-zheng** [comment]
I'm taking this on because it blocks #8.

The compiler-integrated REPL has the filename `<REPL Input>`, which is invalid.
```
$ build/buildbot_linux/swift-linux-x86_64/bin/swift
***  You are running Swift's integrated REPL,  ***
***  intended for compiler and stdlib          ***
***  development and testing purposes only.    ***
***  The full REPL is built as part of LLDB.   ***
***  Type ':help' for assistance.              ***
(swift) import TensorFlow
(swift) let x = Tensor(1)
2018-05-01 21:34:33.631820: E tensorflow/core/common_runtime/executor.cc:660] Executor failed to create kernel. Invalid argument: Node 'op.<REPL Input>.1.16': Node name contains invalid characters
	 [[Node: tfc_func_main.tf_partition = main.tf_partition[_device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Fatal error: Node 'op.<REPL Input>.1.16': Node name contains invalid characters
```

**Comment by ToucheSir** [comment]
The only thing I could think of was (for emoji specifically) using the codepoint number (e.g. :bird: becomes `U1F426`). On second thought, though, that doesn't seem like it'd provide a lot of value over just removing the character.

On an unrelated note, it's great to be able to see and follow the development of this. Looking forward to trying out all of the wonderful new features!

**Comment by rxwei** [comment]
@dan-zheng To unblock compiler integrated repos, the shortest path we can take is to replace spaces with underscores. This issue should be left open. Thanks!

**Comment by dan-zheng** [comment]
An alternative to removing invalid characters is to replace them with `_`. That may look nicer for some filenames, but falls apart for Unicode characters.
* `<REPL Input>`
  * Removal: `REPLInput`
  * Underscore: `_REPL_Input_`
* `Swift for TensorFlow.playground`
  * Removal: `SwiftforTensorFlow.playground`
  * Underscore: `Swift_for_TensorFlow.playground`
* `😃🐦😎asdf`
  * Removal: `asdf`
  * Underscore: `____________asdf`

I'll go ahead and use underscores for now to unblock #8, but I'll leave this issue open.
A robust escaping mechanism should handle unicode characters (using `llvm::UTF8` or some other means) and be reversible.

**Comment by rxwei** [comment]
@dan-zheng Could you cherry-pick and move this one to JIRA too?
