### ISSUE TITLE
Python linking in xcode

### ISSUE THREAD

**Issue by pnorridge** [google/swift#24]
Probably my inexperience, but I can't get the linking to work when I use "import Python" in Xcode -- it throws up a lot of undefined symbols. Is there a particular flag required?

**Comment by dan-zheng** [comment]
Could you share the exact error, including the undefined symbols?

This may be related to #5, please read that thread for more information.
Since `libswiftPython.so` isn't yet linked by default, the `-lswiftPython` flag needs to be manually added.

**Comment by pnorridge** [comment]
I saw #5  and suspect it is the same problem. I tried adding -lswiftPython in 'Other Linker Flags', but it didn't seem to help. I also wanted to try adding libswiftPython.so to 'Linked Frameworks and Libraries' (since this solved problems on tensorflow libraries), but I couldn't find the file. Where should I be looking for it?

Report is attached.
[Build target TFTest_2018-05-02T20-59-24.txt](https://github.com/google/swift/files/1968718/Build.target.TFTest_2018-05-02T20-59-24.txt)

**Comment by dan-zheng** [comment]
The undefined symbols are actually functions from the Python library, not from `libswiftPython.so`:

```
Undefined symbols for architecture x86_64:
  "_PyBool_FromLong", referenced from:
      _$SSb6Python0A11ConvertibleA2aBP11pythonValueAA02PyD0VvgTW in libswiftPython.a(Python.o)
      _$S6Python7PyValueV14booleanLiteralACSb_tcfC in libswiftPython.a(Python.o)
      _$S6Python7PyValueVs27ExpressibleByBooleanLiteralAAsADP07booleanG0x0fG4TypeQz_tcfCTW in libswiftPython.a(Python.o)
  "_PyBool_Type", referenced from:
```

On Mac, the Python library is located at `/System/Library/Frameworks/Python.framework/Versions/2.7/Python`.

Can you confirm that it exists? You can also check that it contains the undefined symbols by running:
```
$ nm -g /System/Library/Frameworks/Python.framework/Versions/2.7/Python | grep _PyBool_FromLong
000000000000b373 T _PyBool_FromLong
```

I'm not sure why the library isn't being linked, it might be related to your Python environment. If you manually add a flag to link the library, things should work.

**Comment by pnorridge** [comment]
Thanks Dan - that gave enough clues. Based on [TN2328 from Apple](https://developer.apple.com/library/content/technotes/tn2328/_index.html), I added Python.framework explicitly in the Xcode sidebar and that seems to have fixed the problem. (The TN is for Xcode 5, but one way or another helps for 9.)

**Comment by dan-zheng** [comment]
Glad you found a solution!
If more people encounter this issue, I'll add it to the [FAQ](https://github.com/tensorflow/swift/blob/master/FAQ.md).
