### ISSUE TITLE
Use SILPrinter callback mechanism to annotate the printed SIL code

### ISSUE THREAD

**Issue by mhong** [google/swift#29]
https://github.com/google/swift/commit/4e27ff202817914fe8b776788c8245abdccfae8b added code for annotating SIL code with TFPartition markings. 

One follow-up suggestion from clattner is to use sil printer callback before printing each instruction (SILPrinter.cpp:634):

```c++
    for (const SILInstruction &I : *BB) {
      Ctx.printInstructionCallBack(&I);
      if (SILPrintGenericSpecializationInfo) {
        if (auto AI = ApplySite::isa(const_cast<SILInstruction *>(&I)))
          if (AI.getSpecializationInfo() && AI.getCalleeFunction())
            printGenericSpecializationInfo(
                PrintState.OS, "call-site", AI.getCalleeFunction()->getName(),
                AI.getSpecializationInfo(), AI.getSubstitutions());
      }
      print(&I);
    }
```

So we can derive a struct from SILPrintContext, and implement [move] kind of annotations by overriding Ctx.printInstructionCallBack.  This way we hopefully just need to call “print” on the function with the right printer context defined.

Example code:

```c++
/// A print context which records the line numbers where instructions are
/// printed.
struct AnalysisPrintContext : public SILPrintContext {
  AnalysisPrintContext(llvm::raw_ostream &OS) : SILPrintContext(OS) {}

  ~AnalysisPrintContext() override {}

  void printInstructionCallBack(const SILInstruction *I) override {
    OutStream << "XXXX ";
    I->print(OutStream);
  }
};
```

Call site:
```c++
  if (auto *outs = getTFDumpIntermediateStream()) {
    AnalysisPrintContext ctx(*outs);
    fn.print(ctx);
  }
```

One challenge is that in addition to annotating instructions, we also want to annotate BB args ([code here](https://github.com/google/swift/blob/4e27ff202817914fe8b776788c8245abdccfae8b/lib/SILOptimizer/Mandatory/TFPartition.cpp#L1877)). So the current callback mechanism on inst level is not sufficient. One option is to extend the SILPrinter callback infra to support annotating BB args.

**Comment by lattner** [comment]
Makes sense.  It would be great to upstream such an extension, I suspect that the swift.org folks would take such a patch with no concern.

**Comment by rxwei** [comment]
Moved to [SR-7669](https://bugs.swift.org/browse/SR-7669).
