### ISSUE TITLE
Will the Tensorflow for Swift open source community be releasing more examples with large models instead of the just the MNIST.swift file?

### ISSUE THREAD

**Issue by shyamalschandra** [google/swift#3]
I am trying to port the tensorflow model python examples into tensorflow for swift examples to create a zoo of examples for others.  

I looked at the documentation at: https://www.tensorflow.org/api_docs/swift/ but it is not clear how the new components match with their python counterparts.  I also went to the swift source code under stdlib/public/Tensorflow/ or stdlib/private/Tensorflow but there is no table that matches the function in swift to the function in python api.  Should I go ahead and experiment by trial-and-error or is this going to be provided by someone in the community?  Is the Tensorflow for Swift incomplete because I don't see anything like the tfjs documentation with examples? (e.g. https://js.tensorflow.org/api/0.6.1/ )

The only thing I could find was the video from the TensorFlow Dev Summit:
https://youtu.be/Yze693W4MaU?t=12m59s

Thanks in advance!

**Comment by zachgrayio** [comment]
A migration guide of sorts might allow the community to more easily lend a hand in the effort to create a Swift model zoo.

**Comment by rxwei** [comment]
Yes, we will add more models, including basic conv nets and an RL agent. Today there are constraints in the language and the compiler so we wanted to be careful and just show some super basic examples (like MNIST). 

Also, this project is in very early stage, and it's not not meant for general use. Today we encourage developers to find bugs, hack on it, and read the design docs to explore underlying technology!
