### ISSUE TITLE
Python Interoperability bug ?

### ISSUE THREAD

**Issue by kenmaz** [google/swift#6]
I'm not sure this bug is related to google/swift or tensorflow/swift.

[This document](https://github.com/tensorflow/swift/blob/master/docs/PythonInteroperability.md) say you can use python api from Swift code.

So I installed [pre-build package ](https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2018-04-26-a-osx.pkg) and run following code, but this code dose not work.
  
```swift
import Python
let np = Python.import("numpy")
let ary = np.array([1,2,3])
print(ary)

// ERROR:
// main.swift:3:19: error: cannot call value of non-function type 'PyValue'
// let ary = np.array([1,2,3])
```

Instead following code is works.

```swift
import Python
let np = Python.import("numpy")
let ary = np.array.call(with:[1,2,3])
print(ary)

//=> [1 2 3]
```

Is this documentation bug or spec ?

Environment: 
- macOS High Sierra (v10.13.4)
- [swift-tensorflow-DEVELOPMENT-2018-04-26-a-osx.pkg](https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2018-04-26-a-osx.pkg)

**Comment by ToucheSir** [comment]
Based on [this section](https://github.com/tensorflow/swift/blob/master/docs/PythonInteroperability.md#dynamically-callable-types) of the python interop document, there are additional changes required on the Swift side before your first code sample can function as expected. That said, the first example in the document appears to use the (presumably not-yet-implemented) `@dynamicCallable` syntax?

**Comment by dan-zheng** [comment]
Currently, you have to call `np.array.call(with: [1, 2, 3])`.
The need to call `.call(with)` explicitly will go away with the [Dynamic Callable proposal](https://gist.github.com/lattner/a6257f425f55fe39fd6ac7a2354d693d), but it is still yet to be implemented.
